<script lang="typescript">
    import { createEventDispatcher, getContext } from 'svelte'
    import { Text, Button, Dropdown, Address } from 'shared/components'
    import { setClipboard } from 'shared/lib/helpers'

    export let locale
    export let generateAddress = (accountId) => {}
    export let isGeneratingAddress = false

    const dispatch = createEventDispatcher()
    const accounts = getContext('walletAccounts')
    const currentAccount = getContext('selectedAccount')

    $: selectedAccount = $currentAccount || $accounts[0]

    const handleDropdownSelect = (item) => {
        selectedAccount = item
    }
    const generateNewAddress = () => {
        generateAddress(selectedAccount.id)
    }
    const handleCloseClick = () => {
        dispatch('previous')
    }
</script>

<div class="w-full h-full flex flex-col justify-between p-8">
    <div class="w-full">
        <Text type="h5" classes="mb-6">{locale('general.receive_funds')}</Text>
        <div>
            {#if !$currentAccount}
                <div class="block mb-8 w-full">
                    <Text type="h5" classes="mb-4">{locale('general.account')}</Text>
                    <Dropdown valueKey={'name'} value={selectedAccount.name} items={$accounts} onSelect={handleDropdownSelect} />
                </div>
            {/if}
            <div class="w-full mb-8 block">
                <Text type="h5" classes="mb-4">{locale('general.your_address')}</Text>
                <Address autoGenerated {isGeneratingAddress} address={selectedAccount.address} {locale} />
            </div>
            <Button secondary disabled={isGeneratingAddress} classes="w-full mb-4" onClick={generateNewAddress}>
                {locale('general.generate_new_address')}
            </Button>
        </div>
    </div>
    <!-- Action -->
    <div class="w-full flex flex-row justify-between px-2">
        <Button secondary classes="-mx-2 w-1/2" onClick={handleCloseClick}>{locale('actions.close')}</Button>
        <Button classes="-mx-2 w-1/2" onClick={() => setClipboard(selectedAccount.address)}>
            {locale('general.copy_address')}
        </Button>
    </div>
</div>
