<script lang="typescript">
    import { fly } from 'svelte/transition'
    import { Text, Button, Dropdown, Address } from 'shared/components'

    export let locale
    export let mobile
    export let accounts

    let destinationAccount: number
    let yourAddress: string = 'iot1q9f0mlq8yxpx2nck8a0slxnzr4ef2ek8f5gqxlzd0wasgp73utryjtzcp98'
    let loadingAddress = false

    const handleSelecDestinationAddress = (value) => {
        destinationAccount = value
    }

    const generateNewAddress = () => {
        loadingAddress = true
        setTimeout(() => {
            loadingAddress = false
        }, 2000)
    }
</script>

{#if mobile}
    <div>foo</div>
{:else}
    <div class="" transition:fly={{ x: 360, duration: 280, opacity: 0 }}>
        <div class="flex flex-row mb-6">
            <Text type="h5">{locale('general.receive_funds')}</Text>
        </div>
        <div>
            <to class="block mb-8">
                <Text type="h5" classes="mb-4">{locale('general.your_address')}</Text>
                <Dropdown
                    value={destinationAccount ? accounts.find((acc) => acc.value === destinationAccount).label : accounts[0].label}
                    items={accounts}
                    onSelect={handleSelecDestinationAddress} />
            </to>
            <address class="w-full mb-8 block">
                <Text type="h5" classes="mb-4">{locale('general.your_address')}</Text>
                <Address autoGenerated loading={loadingAddress} address={yourAddress} {locale} />
            </address>
        </div>
        <div>
            <Button disabled={loadingAddress} classes="w-full" onClick={() => generateNewAddress()}>
                {locale('general.generate_new_address')}
            </Button>
        </div>
    </div>
{/if}
