<script lang="typescript">
    import { createEventDispatcher } from 'svelte'
    import { fly } from 'svelte/transition'
    import { Text, Button, Dropdown, Address } from 'shared/components'
    import { setClipboard } from 'shared/lib/helpers'

    export let locale
    export let mobile

    export let accounts
    export let account
    export let onGenerateAddress = (accountId) => {}
    export let isGeneratingAddress = false

    const dispatch = createEventDispatcher()

    $: selectedAccount = account || accounts.map((acc) => ({ ...acc, label: acc.name }))[0]

    const handleToSelect = (item) => {
        selectedAccount = item
    }

    const generateNewAddress = () => {
        onGenerateAddress(selectedAccount.id)
    }

    const handleCloseClick = () => {
        dispatch('next')
    }
</script>

{#if mobile}
    <div>foo</div>
{:else}
    <div class="w-full h-full flex flex-col justify-center" transition:fly={{ x: 360, duration: 280, opacity: 0 }}>
        <div class="w-full">
            <Text type="h5" classes="mb-6">{locale('general.receive_funds')}</Text>
            <div>
                {#if !account}
                    <div class="block mb-8 w-full">
                        <Text type="h5" classes="mb-4">{locale('general.account')}</Text>
                        <Dropdown
                            value={selectedAccount.label}
                            items={accounts.map((acc) => ({ ...acc, label: acc.name }))}
                            onSelect={handleToSelect} />
                    </div>
                {/if}
                <div class="w-full mb-8 block">
                    <Text type="h5" classes="mb-4">{locale('general.your_address')}</Text>
                    <Address autoGenerated loading={isGeneratingAddress} address={selectedAccount.address} {locale} />
                </div>
                <Button secondary disabled={isGeneratingAddress} classes="w-full mb-4" onClick={generateNewAddress}>
                    Generate new address
                </Button>
            </div>
        </div>
        <!-- Action -->
        <div class="w-full flex flex-row justify-between px-2">
            <Button secondary classes="-mx-2 w-1/2" onClick={() => handleCloseClick()}>Close</Button>
            <Button classes="-mx-2 w-1/2" onClick={() => setClipboard(selectedAccount.address)}>Copy Address</Button>
        </div>
    </div>
{/if}
