env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
#  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
overrides:
  - files: '**/*.svelte'
    processor: 'svelte3/svelte3'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  extraFileExtensions: '.svelte'
  project: './tsconfig.json'
  sourceType: module
  tsconfigRootDir: './'
plugins:
  - '@typescript-eslint'
  - 'svelte3'
rules:
  arrow-body-style: off
  arrow-spacing: off
  eol-last: off
  func-call-spacing: off
  indent:
    - off
    - 4
  linebreak-style:
    - off
    - unix
  no-alert: off
  no-console:
    - off
    - allow:
        - error
        - warn
  no-empty: off
  no-extra-boolean-cast: off
  no-extra-parens: off
  no-extra-semi: off
  no-return-await: off
  no-useless-escape: off
  no-undef: off
  no-underscore-dangle: off
  no-unreachable: off
  no-unused-vars: off
  prefer-arrow-callback: off
  prefer-const: off
  prefer-destructuring: off
  quotes:
    - off
    - single
  semi:
    - off
    - never
  spaced-comment: off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/unbound-method': off
settings:
  'svelte3/typescript': true
