arrowParens: always
bracketSpacing: true
embeddedLanguageFormatting: auto
endOfLine: lf
printWidth: 120
semi: false
singleQuote: true
tabWidth: 4
trailingComma: es5
useTabs: false
plugins:
  - prettier-plugin-svelte
overrides:
  - files: '*.svelte'
    options:
      parser: 'svelte'
