arrowParens: always
bracketSpacing: true
embeddedLanguageFormatting: auto
endOfLine: lf
plugins:
    - 'prettier-plugin-svelte'
printWidth: 120
semi: false
singleQuote: true
tabWidth: 4
trailingComma: es5
useTabs: false
