commit_message: '[ci skip]'
files:
  - source: packages/shared/locales/en.json
    translation: /packages/shared/locales/%two_letters_code%.json
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
