export const menuState = {
    enabled: true,
    strings: {
        // APP_NAME is replaced by Webpack
        // eslint-disable-next-line no-undef
        about: `About ${APP_NAME}`,
        checkForUpdates: 'Check for Updates',
        settings: 'Settings',
        general: 'General',
        security: 'Security',
        advanced: 'Advanced',
        errorLog: 'Error Log',
        diagnostics: 'Diagnostics',
        logout: 'Log Out',
        hide: 'Hide',
        hideOthers: 'Hide Others',
        showAll: 'Show All',
        quit: 'Quit',
        edit: 'Edit',
        undo: 'Undo',
        redo: 'Redo',
        cut: 'Cut',
        copy: 'Copy',
        paste: 'Paste',
        selectAll: 'Select All',
        wallet: 'Wallet',
        addWallet: 'Add Account',
        help: 'Help',
        troubleshoot: 'Troubleshoot',
        faq: 'FAQ',
        documentation: 'Documentation',
        discord: 'Discord',
        reportAnIssue: 'Report an Issue',
        version: 'Version {version}',
    },
}
