export let menuState = {
    loggedIn: false,
    enabled: true,
    strings: {
        about: "About Firefly",
        checkForUpdates: "Check for Updates",
        settings: "Settings",
        generalSettings: "General Settings",
        security: "Security",
        advancedSettings: "Advanced Settings",
        errorLog: "Error Log",
        logout: "Log Out",
        hide: "Hide",
        hideOthers: "Hide Others",
        showAll: "Show All",
        quit: "Quit",
        edit: "Edit",
        undo: "Undo",
        redo: "Redo",
        cut: "Cut",
        copy: "Copy",
        paste: "Paste",
        selectAll: "Select All",
        wallet: "Wallet",
        send: "Send Funds",
        receive: "Receive Funds",
        addAccount: "Add Account",
        help: "Help",
        troubleshoot: "Troubleshoot",
        faq: "FAQ",
        documentation: "Documentation",
        discord: "Discord",
        reportAnIssue: "Report an Issue"
    }
}
