export enum SettingsIcons {
    profile = 'info',
    theme = 'theme',
    language = 'language',
    currency = 'currency',
    notifications = 'bell',
    exportStronghold = 'export',
    appLock = 'lock3',
    changePassword = 'lock2',
    changePincode = 'lock',
    resyncAccounts = 'sync',
    deleteProfile = 'reset',
    deepLinks = 'link',
    developerMode = 'dev',
    nodeSettings = 'settings',
    proofOfWork = 'work',
    errorLog = 'warning',
    diagnostics = 'tools',
    stateExport = 'export',
    troubleshoot = 'tools',
    documentation = 'doc',
    faq = 'speech',
    discord = 'discord',
    about = 'help',
}
