export enum SettingsIcons {
    profile = 'info',
    theme = 'theme',
    language = 'language',
    currency = 'currency',
    notifications = 'bell',
    networkStatus = 'view',
    exportStronghold = 'export',
    appLock = 'lock3',
    changePassword = 'lock2',
    changePincode = 'lock',
    balanceFinder = 'sync',
    hiddenAccounts = 'view',
    deleteProfile = 'reset',
    deepLinks = 'link',
    developerMode = 'dev',
    network = 'settings',
    proofOfWork = 'work',
    errorLog = 'warning',
    diagnostics = 'tools',
    migrateLedgerIndex = 'ledger',
    stateExport = 'export',
    troubleshoot = 'tools',
    documentation = 'doc',
    faq = 'speech',
    discord = 'discord',
    reportAnIssue = 'help',
}
