export enum DrawerId {
    AccountActions = 'accountActions',
    AccountSwitcher = 'accountSwitcher',
    CreateAccount = 'createAccount',
    SelectedActivity = 'selectedActivity',
    Profile = 'profile',
    Send = 'send',
    Receive = 'receive',
    SelectedToken = 'selectedToken',
    Legal = 'legal',
    EnterPassword = 'enterPassword',
    AddReferences = 'addReferences',
    AddExpiration = 'addExpiration',
    Confirm = 'confirm',
    CustomizeAccount = 'customizeAccount',
    BalanceBreakdown = 'balanceBreakdown',
    DeleteAccount = 'deleteAccount',
    Filter = 'filter',
}
