export enum DrawerId {
    AccountActions = 'accountActions',
    AccountSwitcher = 'accountSwitcher',
    CreateAccount = 'createAccount',
    SelectedActivity = 'selectedActivity',
    Profile = 'profile',
    Send = 'send',
    Receive = 'receive',
    SelectedToken = 'selectedToken',
    Legal = 'legal',
    EnterPassword = 'enterPassword',
    References = 'references',
    Expiration = 'expiration',
    Confirm = 'confirmation',
    CustomizeAccount = 'customizeAccount',
    BalanceBreakdown = 'balanceBreakdown',
    DeleteAccount = 'deleteAccount',
    Filter = 'filter',
    DateTimePicker = 'dateTimePicker',
    NetworkStatus = 'networkStatus',
    LegalUpdate = 'LegalUpdate',
}
