export * from './organization.interface'
export * from './participation.interface'
export * from './proposal-state.interface'
export * from './proposal.interface'
export * from './proposals-details.interface'
