export { default as ChangePasswordView } from './ChangePasswordView.svelte'
export { default as HiddenAccountsView } from './HiddenAccountsView.svelte'
export { default as LanguageView } from './LanguageView.svelte'
export { default as SettingsIndexView } from './SettingsIndexView.svelte'
export { default as ThemeView } from './ThemeView.svelte'
