export { default as ChangePasswordView } from './ChangePasswordView.svelte'
export { default as DeleteProfileView } from './DeleteProfileView.svelte'
export { default as DiagnosticsView } from './DiagnosticsView.svelte'
export { default as ErrorLogView } from './ErrorLogView.svelte'
export { default as LanguageView } from './LanguageView.svelte'
export { default as SettingsIndexView } from './SettingsIndexView.svelte'
export { default as ThemeView } from './ThemeView.svelte'
export { default as WalletFinderView } from './WalletFinderView.svelte'
