export enum OnboardingRoute {
    AppSetup = 'appSetup',
    Backup = 'backup',
    Balance = 'balance',
    ClaimRewards = 'claimRewards',
    Congratulations = 'congratulations',
    LedgerSetup = 'ledgerSetup',
    Migration = 'migrate',
    Network = 'network',
    Password = 'password',
    ProfileSetup = 'profileSetup',
    Protection = 'protect',
    Recovery = 'recovery',
    Secure = 'secure',
    Welcome = 'welcome',
}
