export enum OnboardingRoute {
    Welcome = 'welcome',
    AppSetup = 'appSetup',
    Profile = 'profile',
    Setup = 'setup',
    Create = 'create',
    Secure = 'secure',
    Password = 'password',
    LedgerSetup = 'ledgerSetup',
    Protect = 'protect',
    Network = 'network',
    Backup = 'backup',
    Import = 'import',
    Migrate = 'migrate',
    Balance = 'balance',
    ClaimRewards = 'claimRewards',
    Congratulations = 'congratulations',
}
