import { SECONDS_PER_MILESTONE } from '@core/network'
import { MILLISECONDS_PER_SECOND } from '@core/utils'

const INTERVAL_IN_SECONDS = SECONDS_PER_MILESTONE

export const PROPOSAL_STATUS_POLL_INTERVAL = INTERVAL_IN_SECONDS * MILLISECONDS_PER_SECOND
