<script>
    import { Icon } from 'shared/components'
    export let address = undefined
    export let classes = ''
    export let locale = undefined
    export let autoGenerated = false
    export let loading = false
</script>

<style type="text/scss">
    address-input {
        display: flex;
        position: relative;
        textarea {
            resize: none;
            min-height: 72px;
            width: 100%;
            padding: 19px 50px 19px 13px;
            color: var(--text-secondary-color);
            background: var(--element-bg-color);
            border-color: var(--line-separator-color);
            border-radius: 10px;
            box-shadow: -2px -2px 4px rgba(255, 255, 255, 0.2), 0px 4px 8px rgba(65, 114, 248, 0.08);
            font-size: 12px;
            line-height: 140%;
            font-weight: 700;
            &.autoGenerated {
                padding: 19px 50px;
            }
        }
        :global(svg) {
            position: absolute;
            top: 50%;
            left: 12px;
            transform: translateY(-50%);
        }
        :global(svg.right) {
            position: absolute;
            left: inherit;
            right: 12px;
            transform: translateY(-50%);
        }
        :global(svg path) {
            fill: var(--button-secondary-icon-color);
        }

        .loading {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            position: relative;
            min-height: 72px;
            width: 100%;
            padding: 19px;
            background: var(--element-bg-color);
            border-color: var(--line-separator-color);
            border-radius: 10px;
            box-shadow: -2px -2px 4px rgba(255, 255, 255, 0.2), 0px 4px 8px rgba(65, 114, 248, 0.08);
            span {
                width: 100%;
                height: 12px;
                background: linear-gradient(to right, #eef4ff 8%, #eef4ff4d 18%, #eef4ff 33%);
                background-size: 1200px 100px;
                animation: skeleton 1s forwards linear infinite;
            }
            @keyframes skeleton {
                0% {
                    background-position: -500px 0;
                }
                100% {
                    background-position: 500px 0;
                }
            }
        }
    }
</style>

<address-input class={classes}>
    {#if !autoGenerated}
        <textarea bind:value={address} placeholder={locale('general.add_address')} />
        <Icon icon="qr" classes="right" />
    {:else if loading}
        <div class="loading"><span /> <span /></div>
    {:else}
        <div class="flex w-full">
            <Icon icon="qr" />
            <textarea class:autoGenerated disabled value={address} />
            <Icon icon="copy" classes="right" />
        </div>
    {/if}
</address-input>
