---
name: Found a bug?
description: Fill in this form to report it, and help us improve
title: '[Bug report]: '
labels: 'bug report'

body:
    - type: markdown
      attributes:
          value: '# Reporting a bug'
    - type: markdown
      attributes:
          value: |
              Thank you for helping us make Firefly better, by reporting a bug you have found. This issue may already be reported! Please search on the [issue tracker](https://github.com/iotaledger/firefly/issues?q=is%3Aissue+is%3Aopen+label%3Atype%3Abug) before creating one. This form is for bugs only and not for help or support using this application. Please visit the [help and support discussions forum](https://github.com/iotaledger/firefly/discussions/categories/help-support) or join our [discord](https://discord.iota.org/) for help.

    - type: markdown
      attributes:
          value: '## Firefly application details'    
    
    - type: input
      id: version
      attributes:
          label: Version
          description: What version of Firefly are you using? (Select all that apply)
          placeholder: "1.4.0"
      validations:
          required: true

    - type: markdown
      attributes:
          value: '## Issue report'

    - type: textarea
      id: description
      attributes:
          label: Description
          description: Briefly describe the issue.
      validations:
          required: true

    - type: textarea
      id: expected_behaviour
      attributes:
          label: Expected behaviour
          description: A concise description of what you expected to happen.
      validations:
          required: true

    - type: textarea
      id: actual_behaviour
      attributes:
          label: Actual behaviour
          description: A concise description of what actually happened.
      validations:
          required: true
    
    - type: dropdown
      id: can_repro
      attributes:
          label: Can the issue reliably be reproduced?
          options:
              - 'Yes'
              - 'No'
      validations:
          required: true

    - type: textarea
      id: repro_steps
      attributes:
          label: Steps to reproduce the issue
          description: Explain how the maintainer can reproduce the issue.
          placeholder: |
              1.
              2.
              3.
              ...
    
    - type: markdown
      attributes:
          value: '## Your machine'
          
    - type: dropdown
      id: os
      attributes:
          label: Operating System
          description: Which OS does this issue occur on? (Select all that apply)
          multiple: true
          options:
            - Linux
            - Mac
            - Windows
      validations:
          required: true
          
    - type: textarea
      id: diagnostics
      attributes:
          label: Diagnostics
          description: Paste the information from the Diagnostics popup accessible in the Firefly main menu or settings page.
          render: shell
          
    - type: markdown
      attributes:
          value: '## Use of Firefly'
          
    - type: dropdown
      id: profile_role
      attributes:
          label: Developer Profile
          description: Are you using a developer profile?
          multiple: false
          options:
            - "No"
            - "Yes"
      validations:
          required: true
          
    - type: dropdown
      id: profile_type
      attributes:
          label: Profile Type
          description: Are you using a hardware wallet or software wallet?
          multiple: false
          options:
            - Software (Stronghold)
            - Hardware (Ledger)
      validations:
          required: true
          
    - type: dropdown
      id: staking_status
      attributes:
          label: Staking
          description: What is the state of staking in your profile?
          multiple: false
          options:
            - Actively staking
            - Previously staked
            - Never staked
      validations:
              
    - type: markdown
      attributes:
          value: '## Error information'
          
    - type: dropdown
      id: crash_info
      attributes:
          label: Crash Status
          description: Did Firefly crash, hang or freeze?
          multiple: false
          options:
            - "None of the above"
            - Infinite loading symbol
            - Non-responsive
            - White screen
            - Application closed
      validations:
        required: true
          
    - type: textarea
      id: error_messages
      attributes:
          label: Error Messages
          description: Did any error messages display on the screen? If so what was the message?

    - type: textarea
      id: error_logs
      attributes:
          label: Error Logs
          description: Paste the latest errors from the error log, accessible in the Firefly main menu or settings page
          render: shell

    - type: markdown
      attributes:
          value: '## Declarations'

    - type: checkboxes
      id: duplicate_declaration
      attributes:
          label: Duplicate declaration
          description: Please confirm that you are not creating a duplicate issue.
          options:
              - label: I have searched the issues tracker this issue and there is none
                required: true

    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/iotaledger/firefly/blob/53b11691345897703cc3b2cfd3caa830bc2ff949/.github/CODE_OF_CONDUCT.md).
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
