export enum IllustrationEnum {
    BalanceDesktop = 'balance-desktop',
    WhiteArrow = 'white-arrow',
    LedgerInstallNewAppDesktop = 'ledger-install-new-app-desktop',
    LedgerLiveUpdatedDesktop = 'ledger-live-updated-desktop',
    LedgerConnected2Desktop = 'ledger-connected-2-desktop',
    LedgerSearchAppsDesktop = 'ledger-search-apps-desktop',
    LedgerInstallAppsDesktop = 'ledger-install-apps-desktop',
    LedgerCloseLiveDesktop = 'ledger-close-live-desktop',
    LedgerBackgroundLiveDesktop = 'ledger-background-live-desktop',
    LedgerPinDesktop = 'ledger-pin-desktop',
    LedgerOpenAppDesktop = 'ledger-open-app-desktop',
    LedgerSupport = 'ledger-support',
    ShimmerInfoBg = 'shimmer-info-bg',
    AssemblyInfoBg = 'assembly-info-bg',
    StakingNotification = 'staking-notification',
    EmptyCollectibles = 'empty-collectibles',
}
