export { default as Splash } from '@shared-routes/Splash.svelte'
export { default as Onboarding1 } from '@shared-routes/onboarding/Onboarding1.svelte'
export { default as Legal } from '@shared-routes/onboarding/Legal.svelte'
export { default as Setup } from '@shared-routes/setup/Setup.svelte'
export { default as Password } from '@shared-routes/protect/Password.svelte'
export { default as Protect } from '@shared-routes/protect/Protect.svelte'
export { default as Pin } from '@shared-routes/protect/Pin.svelte'
