import { AccountToCreate, AccountIdentifier, ListMessagesFilter } from '../../../../api-wrapper/account';
import { Transfer } from '../../../../api-wrapper/message';
export declare function init(storagePath?: string): void;
export declare function onMessage(cb: (payload: any) => void): void;
export declare function createAccount(account: AccountToCreate): Promise<void>;
export declare function removeAccount(accountId: AccountIdentifier): Promise<void>;
export declare function getAccount(accountId: AccountIdentifier): Promise<void>;
export declare function getAccounts(): Promise<void>;
export declare function syncAccounts(): Promise<void>;
export declare function generateAddress(accountId: AccountIdentifier): Promise<void>;
export declare function listMessages(accountId: AccountIdentifier, filters?: ListMessagesFilter): Promise<void>;
export declare function listAddresses(accountId: AccountIdentifier, unspent?: boolean): Promise<void>;
export declare function availableBalance(accountId: AccountIdentifier): Promise<void>;
export declare function totalBalance(accountId: AccountIdentifier): Promise<void>;
export declare function latestAddress(accountId: AccountIdentifier): Promise<void>;
export declare function reattach(accountId: AccountIdentifier, messageId: string): Promise<void>;
export declare function backup(destinationPath: string): Promise<void>;
export declare function restoreBackup(backupPath: string): Promise<void>;
export declare function setStrongholdPassword(password: string): Promise<void>;
export declare function send(fromAccountId: AccountIdentifier, transfer: Transfer): Promise<void>;
export declare function internalTransfer(fromAccountId: AccountIdentifier, toAccountId: AccountIdentifier, amount: number): Promise<void>;
export declare function listenToErrorEvents(): void;
export declare function listenToBalanceChangeEvents(): void;
export declare function listenToNewTransactionEvents(): void;
export declare function listenToConfirmationStateChangeEvents(): void;
export declare function listenToReattachmentEvents(): void;
export declare function listenToBroadcastEvents(): void;
