import { MILLISECONDS_PER_SECOND, SECONDS_PER_MINUTE } from '@core/utils/constants'

const INTERVAL_IN_MINUTES = 1

export const PARTICIPATION_EVENT__STATUS_POLL_INTERVAL =
    INTERVAL_IN_MINUTES * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND
