export const UNLOCK_CONDITION_ADDRESS = 0
export const UNLOCK_CONDITION_STORAGE_DEPOSIT_RETURN = 1
export const UNLOCK_CONDITION_TIMELOCK = 2
export const UNLOCK_CONDITION_EXPIRATION = 3
export const UNLOCK_CONDITION_STATE_CONTROLLER_ADDRESS = 4
export const UNLOCK_CONDITION_GOVERNOR_ADDRESS = 5
export const UNLOCK_CONDITION_IMMUTABLE_ALIAS = 6

export const ADDRESS_TYPE_ED25519 = 0
export const ADDRESS_TYPE_ALIAS = 8
export const ADDRESS_TYPE_NFT = 16

export const OUTPUT_TYPE_TREASURY = 2
export const OUTPUT_TYPE_BASIC = 3
export const OUTPUT_TYPE_ALIAS = 4
export const OUTPUT_TYPE_FOUNDRY = 5
export const OUTPUT_TYPE_NFT = 6

export const ASYNC_UNLOCK_CONDITION_TYPES = [UNLOCK_CONDITION_STORAGE_DEPOSIT_RETURN, UNLOCK_CONDITION_EXPIRATION]
