export type MimeType =
    | 'image/jpeg'
    | 'image/png'
    | 'image/webp'
    | 'image/gif'
    | 'video/x-msvideo'
    | 'video/mp4'
    | 'video/mpeg'
    | 'audio/mpeg'
    | 'audio/wav'
    | 'model/obj'
    | 'model/u3d'
    | 'application/pdf'
    | 'text/plain'
