export enum SupportedMimeType {
    'image/jpeg',
    'image/png',
    'image/gif',
    'video/x-msvideo',
    'video/mp4',
    'video/mpeg',
    'audio/mpeg',
    'audio/wav',
    'model/obj',
    'model/u3d',
    'application/pdf',
    'text/plain',
    'font/ttf',
}
