import { Icon } from '../enums'
import {
    ARROW_LEFT_ICON,
    ASSEMBLY_ICON,
    BACKSPACE_ICON,
    BELL_ICON,
    BIOMETRIC_ICON,
    CALENDAR_ICON,
    CHECKBOX_ICON,
    CHECKBOX_ROUND_ICON,
    CHECKBOX_UNCHECKED_ICON,
    CHECKBOX_UNCHECKED_ROUND_ICON,
    CHECKMARK_ICON,
    CHEVRON_DOWN_ICON,
    CHEVRON_LEFT_ICON,
    CHEVRON_RIGHT_ICON,
    CHEVRON_UP_ICON,
    CHIP_ICON,
    CLOSE_ICON,
    COPY_ICON,
    CURRENCY_ICON,
    CUSTOMIZE_ICON,
    DELETE_ICON,
    DEV_ICON,
    DISCORD_ICON,
    DOC_ICON,
    DOUBLE_CHEVRON_RIGHT_ICON,
    EDIT_ICON,
    EXCLAMATION_ICON,
    EXPORT_ICON,
    FILE_ICON,
    FIREFLY_ICON,
    HELP_ICON,
    HIDE_ICON,
    HISTORY_ICON,
    INFO_FILLED_ICON,
    INFO_ICON,
    IOTA_ICON,
    LANGUAGE_ICON,
    LEDGER_APP_ICON,
    LEDGER_APP_LEGACY_ICON,
    LEDGER_ICON,
    LINK_ICON,
    LOCK2_ICON,
    LOCK3_ICON,
    LOCK_ICON,
    LOGOUT_ICON,
    MINUS_ICON,
    NETWORK_ICON,
    PARCHMENT_ICON,
    PLAY_ICON,
    PLUS_ICON,
    PROFILE_ICON,
    QR_ICON,
    RADIO_ICON,
    RECEIVE_ICON,
    REFRESH_ICON,
    RESET_ICON,
    SEARCH_ICON,
    SECURITY_ICON,
    SEED_ICON,
    SEND_ICON,
    SETTINGS_ICON,
    SHIELD_ICON,
    SHIMMER_ICON,
    SMALL_CHEVRON_DOWN_ICON,
    SMALL_CHEVRON_LEFT_ICON,
    SMALL_CHEVRON_RIGHT_ICON,
    SMALL_CHEVRON_UP_ICON,
    SPEECH_ICON,
    STAKING_ICON,
    STATUS_ERROR_ICON,
    STATUS_SUCCESS_ICON,
    SUCCESS_CHECK_ICON,
    SYNC_ICON,
    THEME_DARK_ICON,
    THEME_ICON,
    THEME_LIGHT_ICON,
    TIMER_ICON,
    TOKENS_ICON,
    TOOLS_ICON,
    TRANSFER_ICON,
    UNLOCK_ICON,
    VIEW_ICON,
    VOTING_ICON,
    WALLET_ICON,
    WARNING_FILLED_ICON,
    WARNING_ICON,
    WIFI_ICON,
    WORK_ICON,
} from '../svgs'

export const ICON_SVG = {
    [Icon.ArrowLeft]: ARROW_LEFT_ICON,
    [Icon.Assembly]: ASSEMBLY_ICON,
    [Icon.Backspace]: BACKSPACE_ICON,
    [Icon.Bell]: BELL_ICON,
    [Icon.Biometric]: BIOMETRIC_ICON,
    [Icon.Calendar]: CALENDAR_ICON,
    [Icon.Checkbox]: CHECKBOX_ICON,
    [Icon.CheckboxRound]: CHECKBOX_ROUND_ICON,
    [Icon.CheckboxUnchecked]: CHECKBOX_UNCHECKED_ICON,
    [Icon.CheckboxUncheckedRound]: CHECKBOX_UNCHECKED_ROUND_ICON,
    [Icon.Checkmark]: CHECKMARK_ICON,
    [Icon.ChevronDown]: CHEVRON_DOWN_ICON,
    [Icon.ChevronLeft]: CHEVRON_LEFT_ICON,
    [Icon.ChevronRight]: CHEVRON_RIGHT_ICON,
    [Icon.ChevronUp]: CHEVRON_UP_ICON,
    [Icon.Chip]: CHIP_ICON,
    [Icon.Close]: CLOSE_ICON,
    [Icon.Copy]: COPY_ICON,
    [Icon.Currency]: CURRENCY_ICON,
    [Icon.Customize]: CUSTOMIZE_ICON,
    [Icon.Delete]: DELETE_ICON,
    [Icon.Dev]: DEV_ICON,
    [Icon.Discord]: DISCORD_ICON,
    [Icon.Doc]: DOC_ICON,
    [Icon.DoubleChevronRight]: DOUBLE_CHEVRON_RIGHT_ICON,
    [Icon.Edit]: EDIT_ICON,
    [Icon.Exclamation]: EXCLAMATION_ICON,
    [Icon.Export]: EXPORT_ICON,
    [Icon.File]: FILE_ICON,
    [Icon.Firefly]: FIREFLY_ICON,
    [Icon.Help]: HELP_ICON,
    [Icon.Hide]: HIDE_ICON,
    [Icon.History]: HISTORY_ICON,
    [Icon.Info]: INFO_ICON,
    [Icon.InfoFilled]: INFO_FILLED_ICON,
    [Icon.Iota]: IOTA_ICON,
    [Icon.Language]: LANGUAGE_ICON,
    [Icon.Ledger]: LEDGER_ICON,
    [Icon.LedgerApp]: LEDGER_APP_ICON,
    [Icon.LedgerAppLegacy]: LEDGER_APP_LEGACY_ICON,
    [Icon.Link]: LINK_ICON,
    [Icon.Lock]: LOCK_ICON,
    [Icon.Lock2]: LOCK2_ICON,
    [Icon.Lock3]: LOCK3_ICON,
    [Icon.Logout]: LOGOUT_ICON,
    [Icon.Minus]: MINUS_ICON,
    [Icon.Network]: NETWORK_ICON,
    [Icon.Parchment]: PARCHMENT_ICON,
    [Icon.Play]: PLAY_ICON,
    [Icon.Plus]: PLUS_ICON,
    [Icon.Profile]: PROFILE_ICON,
    [Icon.Qr]: QR_ICON,
    [Icon.Radio]: RADIO_ICON,
    [Icon.Receive]: RECEIVE_ICON,
    [Icon.Refresh]: REFRESH_ICON,
    [Icon.Reset]: RESET_ICON,
    [Icon.Search]: SEARCH_ICON,
    [Icon.Security]: SECURITY_ICON,
    [Icon.Seed]: SEED_ICON,
    [Icon.Send]: SEND_ICON,
    [Icon.Settings]: SETTINGS_ICON,
    [Icon.Shield]: SHIELD_ICON,
    [Icon.Shimmer]: SHIMMER_ICON,
    [Icon.SmallChevronDown]: SMALL_CHEVRON_DOWN_ICON,
    [Icon.SmallChevronLeft]: SMALL_CHEVRON_LEFT_ICON,
    [Icon.SmallChevronRight]: SMALL_CHEVRON_RIGHT_ICON,
    [Icon.SmallChevronUp]: SMALL_CHEVRON_UP_ICON,
    [Icon.Speech]: SPEECH_ICON,
    [Icon.Staking]: STAKING_ICON,
    [Icon.StatusError]: STATUS_ERROR_ICON,
    [Icon.StatusSuccess]: STATUS_SUCCESS_ICON,
    [Icon.SuccessCheck]: SUCCESS_CHECK_ICON,
    [Icon.Sync]: SYNC_ICON,
    [Icon.Theme]: THEME_ICON,
    [Icon.ThemeDark]: THEME_DARK_ICON,
    [Icon.ThemeLight]: THEME_LIGHT_ICON,
    [Icon.Timer]: TIMER_ICON,
    [Icon.Tokens]: TOKENS_ICON,
    [Icon.Tools]: TOOLS_ICON,
    [Icon.Transfer]: TRANSFER_ICON,
    [Icon.Unlock]: UNLOCK_ICON,
    [Icon.View]: VIEW_ICON,
    [Icon.Voting]: VOTING_ICON,
    [Icon.Wallet]: WALLET_ICON,
    [Icon.Warning]: WARNING_ICON,
    [Icon.WarningFilled]: WARNING_FILLED_ICON,
    [Icon.Wifi]: WIFI_ICON,
    [Icon.Work]: WORK_ICON,
}
