<script lang="typescript">
    import { fly } from 'svelte/transition'
    import { Text, Button, Dropdown, Address } from 'shared/components'

    export let locale
    export let mobile

    // TODO: CLEAN ALL THIS
    enum RECEIVE_TYPES {
        ADDRESS,
    }

    let destinationAccount: number
    let destinationType: RECEIVE_TYPES = null
    let yourAddress: string = 'iot1q9f0mlq8yxpx2nck8a0slxnzr4ef2ek8f5gqxlzd0wasgp73utryjtzcp98'
    let reference
    let loadingAddress = false

    const accounts = [
        { value: 1, label: 'Personal' },
        { value: 2, label: 'Savings' },
    ]

    const handleSelectDestinationClick = (type: RECEIVE_TYPES) => {
        console.log(type)
        destinationType = type
    }
    const handleSelecDestinationAddress = (value) => {
        destinationAccount = value
    }

    const generateNewAddress = () => {
        loadingAddress = true
        setTimeout(() => {
            loadingAddress = false
        }, 2000)
    }
</script>

<style type="text/scss">
    receive {
        :global(button.icon) {
            background-color: var(--app-bg-color);
            border: 1px solid var(--line-separator-color);
        }
        address {
            @apply p-5;
            background-color: var(--line-separator-color);
            border-radius: 16px;
        }
    }
</style>

{#if mobile}
    <div>foo</div>
{:else}
    <receive class="h-full p-8 flex flex-col" transition:fly={{ x: 360, duration: 280, opacity: 0 }}>
        <Text type="h4" classes="text-center mb-10">{locale('general.receive_funds')}</Text>
        {#if destinationType === null}
            <div class="w-full h-full">
                <Button
                    icon="send"
                    classes="w-full mb-5"
                    secondary
                    onClick={() => handleSelectDestinationClick(RECEIVE_TYPES.ADDRESS)}>
                    {locale('general.share_address')}
                    <Text type="p" secondary>{locale('general.scan_qr_or_paste')}</Text>
                </Button>
            </div>
        {:else if destinationType === RECEIVE_TYPES.ADDRESS}
            <div transition:fly={{ x: 360, duration: 280, opacity: 0 }} class="w-full h-full flex flex-col justify-between">
                <div>
                    <to class="block mb-8">
                        <Text type="h5" classes="mb-4">{locale('general.your_address')}</Text>
                        <Dropdown
                            value={destinationAccount ? accounts.find((acc) => acc.value === destinationAccount).label : accounts[0].label}
                            items={accounts}
                            onSelect={handleSelecDestinationAddress} />
                    </to>
                    <address class="w-full mb-8 block">
                        <Text type="h5" classes="mb-4">{locale('general.your_address')}</Text>
                        <Address autoGenerated loading={loadingAddress} address={yourAddress} {locale} />
                    </address>
                </div>
                <div>
                    <Button disabled={loadingAddress} classes="w-full" onClick={() => generateNewAddress()}>
                        {locale('general.generate_new_address')}
                    </Button>
                </div>
            </div>
        {/if}
    </receive>
{/if}
