import { DAYS_PER_WEEK, DAYS_PER_YEAR, MILLISECONDS_PER_DAY } from '@core/utils'

export const PAYOUT_SCHEDULE = 2 * DAYS_PER_WEEK
export const PAYOUT_SCHEDULE_MILLISECONDS = PAYOUT_SCHEDULE * MILLISECONDS_PER_DAY
export const PAYOUTS_IN_1_YEAR = Math.round(DAYS_PER_YEAR / PAYOUT_SCHEDULE)
