import { DAYS_PER_WEEK, DAYS_PER_YEAR, MILLISECONDS_PER_DAY } from '@core/utils'

export const VESTING_PAYOUT_SCHEDULE = 2 * DAYS_PER_WEEK
export const VESTING_PAYOUT_SCHEDULE_MILLISECONDS = VESTING_PAYOUT_SCHEDULE * MILLISECONDS_PER_DAY
export const VESTING_PAYOUTS_IN_1_YEAR = Math.round(DAYS_PER_YEAR / VESTING_PAYOUT_SCHEDULE)
